### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by michaellwest** [meziantou/HttpCache#1]
Thank you very much for making this available. Curious if a couple of features could be added.

* Support HTTP/2
* Adhere to cache-control headers like so the cache would auto-refresh.

**Comment by meziantou** [comment]
Hi,

- The application relies on FiddlerCore to intercept http requests. I don't know if it supports http2. You should ask Telerik for more information.
- Supporting `cache-control` is doable. I haven't plan to implement it but you can do a pull request if you want to contribute :)
